---
- name: Configuring the apache2
  hosts: all
  tasks: 
   - name: install the apache2
     apt:
      name: apache2
      state: present
     notify: check the url response
   - name: Edit the index.html file
     copy:
      content: "Welcome to Hydepark Mansions\n"
      dest: /var/www/html/index.html
     notify: Restart the apache2
  handlers:
   - name: Restart the apache2
     service: 
      name: apache2
      state: restarted
   - name: Check the url response
     uri:
      url: "{{item}}"
      status_code: 200
     with_items:
      - http://192.168.50.3
      - http://192.168.50.4 
...       
